spring:
  application: "Yggdrasil Core"
  profiles:
    active: "live"
server:
  port: 9000
blockchain:
  network: "main"
  p2p:
    port: 9090
    active-connections: 10
    node-name: "yggdrasil-branch"
    peers: "192.168.1.42,192.168.1.2"
    peer-records: 25
    #connection-timeout: 30000