spring:
  application: "Yggdrasil Core"
  profiles:
    active: "live"
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  port: 9000
  shutdown: "graceful"
blockchain:
  network: "main"
  p2p:
    port: 9090
    active-connections: 10
    node-name: "yggdrasil-branch"
    peers: "192.168.1.122"
    peer-records: 25
    #connection-timeout: 30000